version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: local-mysql
    restart: always
    environment:
      MYSQL_DATABASE: localdb
      MYSQL_USER: ${LOCAL_USERNAME}
      MYSQL_PASSWORD: ${LOCAL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - env.properties

volumes:
  mysql-data: